<?php

namespace AjSystem\AdminBundle\Repository;

/**
 * AdministradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministradorRepository extends \Doctrine\ORM\EntityRepository
{
}
