<?php

namespace AjSystem\AdminBundle\Repository;

/**
 * ContasAPagarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContasAPagarRepository extends \Doctrine\ORM\EntityRepository
{
}
