<?php

namespace AjSystem\AdminBundle\Repository;

/**
 * FuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFuncionario($nome = null){

        $qb = $this->createQueryBuilder('f');

        if (!empty($nome)){
            $qb
                ->where("f.active = 1")
                ->where(
                    $qb->expr()->like('f.nome', ':nome')
                )
                ->setParameter('nome',"%{$nome}%");
        }
        return $qb
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }
}
