<?php

namespace AjSystem\AdminBundle\Repository;

/**
 * ServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoRepository extends \Doctrine\ORM\EntityRepository
{
}
